"""edited listing 3

Revision ID: 51dbfe713aba
Revises: 6ef084415882
Create Date: 2023-04-04 13:01:37.971676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51dbfe713aba'
down_revision = '6ef084415882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
