"""location

Revision ID: 107e03dc5049
Revises: fe6d9e2ca5ad
Create Date: 2023-04-03 03:00:35.351373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107e03dc5049'
down_revision = 'fe6d9e2ca5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
