"""remove condition

Revision ID: 719a2ae86955
Revises: fd18a378b6c0
Create Date: 2023-04-14 13:22:22.343505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719a2ae86955'
down_revision = 'fd18a378b6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('condition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
