"""edited listing

Revision ID: e65ec220e657
Revises: e06c663a65e4
Create Date: 2023-04-01 14:38:15.692981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65ec220e657'
down_revision = 'e06c663a65e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('category_name_key', type_='unique')

    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('data')
        batch_op.drop_column('filename')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('category_name_key', ['name'])

    # ### end Alembic commands ###
