"""edited tables 5

Revision ID: fd18a378b6c0
Revises: c9dd08b31157
Create Date: 2023-04-12 07:57:29.546987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd18a378b6c0'
down_revision = 'c9dd08b31157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('item')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('listing_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.drop_constraint('listing_image_listing_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'listing', ['listing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('listing_image_listing_id_fkey', 'listing', ['listing_id'], ['listing_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('listing_category_id_fkey', 'category', ['category_id'], ['category_id'])
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    op.create_table('item',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('item_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='item_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='image_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='image_pkey')
    )
    # ### end Alembic commands ###
