"""Listingimage path

Revision ID: fe6d9e2ca5ad
Revises: e65ec220e657
Create Date: 2023-04-01 16:56:37.256442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6d9e2ca5ad'
down_revision = 'e65ec220e657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
